// ============================================================
// Shared Types for GNSS System Frontend
// These types are used across pages and components.
// They are NOT generated by Orval — they extend backend types
// with frontend-specific fields (device status, telemetry, etc.)
// ============================================================

// ---------- Device types ----------
export type DeviceStatus = "online" | "offline" | "maintenance";

export interface UserDevice {
  id: string;
  name: string;
  speedLimitKmh: number;
  status: DeviceStatus;
  battery: number;
  lat: number;
  lng: number;
  cameraStatus: boolean;
  gnssStatus: boolean;
  lastSeen: string;
  createdAt: string;
}

export interface MqttCredentials {
  deviceId: string;
  mqttUsername: string;
  mqttPassword: string;
  mqttHost: string;
  mqttPort: number;
  mqttProtocol: string;
  topics: Record<string, string>;
}

export interface DeviceDetailInfo extends UserDevice {
  owner: string;
  satellites: number;
  hdop: number;
  vdop: number;
}

export interface SimpleDevice {
  id: string;
  name: string;
}

// ---------- Telemetry types ----------
export interface TelemetryPoint {
  lat: number;
  lng: number;
  speed: number;
  battery: number;
  timestamp: string;
}

// ---------- Alert types ----------
export type AlertType =
  | "speeding"
  | "geofence_exit"
  | "geofence_enter"
  | "signal_loss"
  | "signal_lost"
  | "dangerous_obstacle"
  | "trajectory_deviation"
  | "low_battery";

export interface UserAlert {
  id: string;
  deviceId: string;
  deviceName: string;
  type: AlertType;
  alertType?: string;
  message: string;
  isResolved: boolean;
  timestamp: string;
  createdAt?: string;
  device?: {
    id?: string;
    name?: string;
    [key: string]: unknown;
  };
  /** Optional media attachment */
  media?: {
    type: "image_frame" | "video_chunk";
    url: string;
    thumbnail: string;
    mediaLogId?: string;
  };
}

export const ALERT_TYPE_CONFIG: Record<
  string,
  { label: string; icon: string; badgeClass: string }
> = {
  speeding: {
    label: "Quá tốc độ",
    icon: "🏎️",
    badgeClass: "bg-amber-500/10 text-amber-500 border-amber-500/20",
  },
  geofence_exit: {
    label: "Rời vùng",
    icon: "🗺️",
    badgeClass: "bg-red-500/10 text-red-400 border-red-500/20",
  },
  geofence_enter: {
    label: "Vào vùng",
    icon: "📍",
    badgeClass: "bg-blue-500/10 text-blue-400 border-blue-500/20",
  },
  signal_loss: {
    label: "Mất tín hiệu",
    icon: "📡",
    badgeClass: "bg-slate-500/10 text-slate-400 border-slate-500/20",
  },
  signal_lost: {
    label: "Mất tín hiệu",
    icon: "📡",
    badgeClass: "bg-slate-500/10 text-slate-400 border-slate-500/20",
  },
  dangerous_obstacle: {
    label: "Chướng ngại vật",
    icon: "⚠️",
    badgeClass: "bg-red-500/10 text-red-400 border-red-500/20",
  },
  trajectory_deviation: {
    label: "Lệch quỹ đạo",
    icon: "↗️",
    badgeClass: "bg-violet-500/10 text-violet-400 border-violet-500/20",
  },
  low_battery: {
    label: "Pin yếu",
    icon: "🔋",
    badgeClass: "bg-amber-500/10 text-amber-500 border-amber-500/20",
  },
};

// ---------- Geofence types ----------
export interface GeofenceZone {
  id: string;
  name: string;
  type: "allowed_zone" | "forbidden_zone";
  color: string;
  paths: { lat: number; lng: number }[];
  assignedDevices: string[];
  Devices?: unknown[];
  createdAt: string;
  vertexCount?: number;
}

// ---------- Dashboard types ----------
export interface DashboardDevice {
  id: string;
  name: string;
  status: "online" | "offline";
  lat: number;
  lng: number;
  battery: number;
  hdop: number;
  vdop: number;
  satellites: number;
  maxSatellites: number;
  lastSeen: string;
  type: "rover" | "base" | "relay";
}

export interface DashboardAlert {
  id: string;
  deviceId: string;
  deviceName: string;
  severity: "critical" | "warning" | "info";
  message: string;
  timestamp: string;
  acknowledged: boolean;
}

export interface DashboardMediaLog {
  id: string;
  deviceId: string;
  deviceName: string;
  thumbnail: string;
  objectDetected: string;
  confidence: number;
  timestamp: string;
  resolution: string;
}

export interface DashboardGeofence {
  id: string;
  name: string;
  color: string;
  paths: { lat: number; lng: number }[];
}

// ---------- Admin types ----------
export interface AdminDevice extends UserDevice {
  ownerId: string;
  ownerEmail: string;
}

export interface GlobalDevice {
  id: string;
  name: string;
  ownerEmail: string;
  ownerId: string;
  status: "online" | "offline" | "maintenance";
  lat: number;
  lng: number;
  battery: number;
  speed: number;
  lastSeen: string;
}

export interface AdminGeofence {
  id: string;
  name: string;
  ownerId: string;
  ownerEmail: string;
  pointCount: number;
  deviceCount: number;
  createdAt: string;
}

export interface AdminAlert {
  id: string;
  deviceId: string;
  deviceName: string;
  ownerId: string;
  ownerEmail: string;
  type: string;
  message: string;
  isResolved: boolean;
  hasMedia: boolean;
  timestamp: string;
}

export interface SystemUser {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  status: UserStatus;
  emailVerified: boolean;
  deviceCount: number;
  createdAt: string;
  lastLoginAt: string;
}

// ---------- Statistics types (Admin) ----------
export interface SystemOverview {
  totalUsers: number;
  activeUsers: number;
  totalDevices: number;
  onlineDevices: number;
  totalGeofences: number;
  totalAlerts: number;
}

export interface TelemetryStat {
  date: string;
  points: number;
}

export interface AlertTypeStat {
  name: string;
  count: number;
}

export interface MediaStat {
  date: string;
  images: number;
  videos: number;
}

export type UserRole = "admin" | "user";
export type UserStatus = "active" | "banned";
